# v2 syntax
version: '2'

# Named volumes
volumes:
 # MySQL Data
 devsquad-mysql-data:
  driver: local

services:
 # MySQL (5.7)
 mysql:
  image: mysql:5.7
  container_name: devsquad-mysql
  volumes:
   - devsquad-mysql-data:/var/lib/mysql
  ports:
   - "${DB_LOCAL_PORT}:3306"
  environment:
   - MYSQL_DATABASE=${DB_DATABASE}
   - MYSQL_USER=${DB_USERNAME}
   - MYSQL_PASSWORD=${DB_PASSWORD}
   - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

 # PHP (with Nginx)
 # you can change from nginx to apache, just change session 'image'
 app:
  image: ambientum/php:7.2-nginx
  container_name: devsquad-app
  volumes:
   - .:/var/www/app
  ports:
   - "${APP_PORT}:8080"
  links:
   - mysql